<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "who_shop"
 *
 * Auto generated by Extension Builder 2014-09-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'WHO Shop',
	'description' => 'A simple shop extension',
	'categories' => 'plugin',
	'author' => 'Sebastian Hofer',
	'author_email' => 'sebastian.hofer@s-hofer.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);